"""change post

Revision ID: aa2e6deda760
Revises: a84867f171f2
Create Date: 2024-03-26 13:20:08.346987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aa2e6deda760'
down_revision: Union[str, None] = 'a84867f171f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('text', sa.String(length=100), nullable=False))
    op.drop_column('post', 'title')
    op.drop_column('post', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('content', mysql.VARCHAR(length=1000), nullable=False))
    op.add_column('post', sa.Column('title', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('post', 'text')
    # ### end Alembic commands ###
