version: "3.9"

services:
  uvicorn:
    container_name: uvicorn
    build:
      context: ./web
      dockerfile: Dockerfile
    image: uvicorn
    command: uvicorn --host 0.0.0.0 --port 80 --reload app.main:app
    ports:
      - "80:80"
    volumes:
      - ./web:/home/web/
    env_file:
      - .env
    restart: "no"

  db:
    container_name: db
    image: mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql_db:/var/lib/mysql
    env_file:
      - .env
    restart: "no"

  cache:
    container_name: cache
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes: 
      - cache:/data

volumes:
  mysql_db:
  cache:

